### ISSUE TITLE
Not loading with SD 1.6

### ISSUE THREAD

**Issue by jlitz** [v8hid/infinite-zoom-automatic1111-webui#110]
**Describe the bug**Einfinite zoom not loading

**To Reproduce**
1. Enter these inputs '....'

**Expected behavior**

**Screenshots of error**
If applicable, add screenshots to help explain your problem. Or just dump the error.

windows 11

 Error loading script: infinite-zoom.py
    Traceback (most recent call last):
      File "D:\A1112\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\A1112\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\A1112\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 2, in <module>
        from iz_helpers.ui import on_ui_tabs
      File "D:\A1112\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\iz_helpers\ui.py", line 4, in <module>
        from webui import wrap_gradio_gpu_call
    ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' (D:\A1112\stable-diffusion-webui\webui.py)

**Comment by jlitz** [comment]
thank you  that works

**Comment by tuwonga** [comment]
thanks a lot !

**Comment by alexbofa** [comment]
Fix: https://github.com/v8hid/infinite-zoom-automatic1111-webui/pull/109

**Comment by zzzPitoNzzz** [comment]
Thank you, Master! )
