### ISSUE TITLE
Error when generating

### ISSUE THREAD

**Issue by DawgZter** [v8hid/infinite-zoom-automatic1111-webui#19]
Error completing request1:05,  3.69s/it]
Arguments: ([[0, 'cyberpunk themed world'], ['', ''], ['', '']], 'frames, borderline, text, character, duplicate, error, out of frame, watermark, low quality, ugly, deformed, blur', 8, 7, 50, None, 30, 0, 0, 0, 1, 0, 2, False, 0, 1, 512) {}
Traceback (most recent call last):
  File "/Users/xxxx/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/xxxx/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/xxxx/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/inifnite-zoom.py", line 227, in create_zoom
    write_video(
  File "/Users/xxxx/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/iz_helpers/video.py", line 35, in write_video
    writer.append_data(np_frame)
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 587, in _append_data
    self._initialize()
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 648, in _initialize
    self._write_gen.send(None)
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/imageio_ffmpeg/_io.py", line 509, in write_frames
    codec = get_first_available_h264_encoder()
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/imageio_ffmpeg/_io.py", line 125, in get_first_available_h264_encoder
    compiled_encoders = get_compiled_h264_encoders()
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/imageio_ffmpeg/_io.py", line 59, in get_compiled_h264_encoders
    cmd = [get_ffmpeg_exe(), "-hide_banner", "-encoders"]
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 33, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

Traceback (most recent call last):
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/xxxx/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

**Comment by v8hid** [comment]
> RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

For some reason Imageio can't find the FFMPEG.
Can you tell me what operating system are you using?
And also check that `ffmpeg -version` works or not?

**Comment by GeorgLegato** [comment]
@DawgZter yes, follow the instruction in the Setting tab and the FFPROBE setting. Follow the URL, download your OS-compatible package of FFMPEG, unziip ist somewhere and put that path (like c:\me\ffmpeg\bin or /hom/me/ffmpe/bin) into this window. So the extension will dedicated use this ffmpeg runtime

**Comment by DawgZter** [comment]
@GeorgLegato @v8hid Yep I just had to install ffmpeg, thanks for the help guys!

**Comment by winjoe-z** [comment]
My computer is a mac, and this problem also occurs. How can I solve it?

**Comment by v8hid** [comment]
Hey @winjoe-z 
If you are getting `No ffmpeg exe could be found.` try to re-install FFMPEG 
Maybe this guide can help https://phoenixnap.com/kb/ffmpeg-mac
