### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bbecausereasonss** [v8hid/infinite-zoom-automatic1111-webui#2]
Loading weights [8db0e00911] from C:\Users\xxxx\Deep\stable-diffusion-webui\models\Stable-diffusion\Jelli.ckpt
Applying scaled dot product cross attention optimization.
Weights loaded in 9.4s (load weights from disk: 8.6s, apply weights to model: 0.2s, move model to device: 0.6s).
Error completing request
Arguments: ([['A psychedelic hyper-realistic photo of Jellili person in space, fractal-like patterns, a close up of Jelliperson eye, galaxy in space hyper futuristic, 8k resolution, hyper realistic', '']], 'frames, borderline, text, character, duplicate, error, out of frame, watermark, low quality, ugly, deformed, blur', 8, 7, 50, None, 30, 0, 0, 0, 1, 0, 2, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\inifnite-zoom.py", line 132, in create_zoom
    prompts[min(k for k in prompts.keys() if k >= 0)],
ValueError: min() arg is an empty sequence

Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\xxxx\Deep\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

**Comment by v8hid** [comment]
Hello @bbecausereasonss,

Thank you for sharing the error you encountered. After reviewing the information you provided, it appears that the issue is related to the placement of the prompt.

Based on the `Arguments: ([['A psychedelic hyper-realistic photo of Jellili person in space, fractal-like patterns, a close up of Jelliperson eye, galaxy in space hyper futuristic, 8k resolution, hyper realistic', '']], 'frames, borderline, text, character, duplicate, error, out of frame, watermark, low quality, ugly, deformed, blur', 8, 7, 50, None, 30, 0, 0, 0, 1, 0, 2, False, 0) {}` you shared, it seems that you entered the prompt in the Outpaint Steps field instead of the designated prompt section. To resolve this, please ensure that you input the prompt in the correct section, as shown in the screenshot below:

![Screenshot 2023-04-14 at 6 15 05 PM](https://user-images.githubusercontent.com/62482657/232070999-e109de83-2a75-4661-bd66-d9519fe7f7d6.png)



I hope this solution resolves the problem you were experiencing. If you have any further questions or concerns, please don't hesitate to reach out to me.

**Comment by bbecausereasonss** [comment]
Thank you!
