### ISSUE TITLE
first click on generate fails

### ISSUE THREAD

**Issue by laurentopia** [v8hid/infinite-zoom-automatic1111-webui#35]
I think it needs to wait for model loading

**Comment by TanvirHafiz** [comment]
i also get failed and get this errors

Traceback (most recent call last):
  File "G:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "G:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\Automatic1111\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 154, in create_zoom
    result = create_zoom_single(
  File "G:\Automatic1111\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 241, in create_zoom_single
    current_image = processed.images[0]
IndexError: list index out of range

**Comment by Lancer907** [comment]
> 

same

**Comment by friedvinegar** [comment]
me too

**Comment by ZMSamShark** [comment]
me too
