### ISSUE TITLE
on Upscale: Odd pixel width crashes ffmpeg

### ISSUE THREAD

**Issue by GeorgLegato** [v8hid/infinite-zoom-automatic1111-webui#45]
If upscale factor * output pixel-size => odd width => ffmpeg dies:

720 px width * 1.66 upscale => 1195.2 => 1195 crash

Inputs:
![image](https://user-images.githubusercontent.com/7210708/233510020-8c6b769d-24e6-4b52-929c-df7922659747.png)
![image](https://user-images.githubusercontent.com/7210708/233510047-2a6c7cf2-78cd-4b7d-909a-5b7677f84614.png)
![image](https://user-images.githubusercontent.com/7210708/233510068-5241bdf8-31c4-484c-bccc-41564b7bf403.png)

[swscaler @ 0000022737ce1000] Warning: data is not aligned! This can lead to a speed loss
[libx264 @ 0000022737c8d400] width not divisible by 2 (1195x849)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
gradio call: OSError
╭───────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────╮│ S:\KI\Vladmandic1111\venv\lib\site-packages\imageio_ffmpeg\_io.py:630 in write_frames                                                                                               ││                                                                                                                                                                                     ││   629 │   │   │   try:                                                                                                                                                              ││ ❱ 630 │   │   │   │   p.stdin.write(bb)                                                                                                                                             ││   631 │   │   │   except Exception as err:                                                                                                                                          │╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────╮│ S:\KI\Vladmandic1111\modules\call_queue.py:61 in f                                                                                                                                  ││                                                                                                                                                                                     ││    60 │   │   │   │   pr.enable()                                                                                                                                                   ││ ❱  61 │   │   │   res = list(func(*args, **kwargs))                                                                                                                                 ││    62 │   │   │   if shared.cmd_opts.profile:                                                                                                                                       ││                                                                                                                                                                                     ││ S:\KI\Vladmandic1111\modules\call_queue.py:39 in f                                                                                                                                  ││                                                                                                                                                                                     ││    38 │   │   │   try:                                                                                                                                                              ││ ❱  39 │   │   │   │   res = func(*args, **kwargs)                                                                                                                                   ││    40 │   │   │   finally:                                                                                                                                                          ││                                                                                                                                                                                     ││                                                                               ... 4 frames hidden ...                                                                               ││                                                                                                                                                                                     ││ S:\KI\Vladmandic1111\venv\lib\site-packages\imageio\plugins\ffmpeg.py:600 in _append_data                                                                                           ││                                                                                                                                                                                     ││   599 │   │   │   # Write. Yes, we can send the data in as a numpy array                                                                                                            ││ ❱ 600 │   │   │   self._write_gen.send(im)                                                                                                                                          ││   601                                                                                                                                                                               ││                                                                                                                                                                                     ││ S:\KI\Vladmandic1111\venv\lib\site-packages\imageio_ffmpeg\_io.py:637 in write_frames                                                                                               ││                                                                                                                                                                                     ││   636 │   │   │   │   )                                                                                                                                                             ││ ❱ 637 │   │   │   │   raise IOError(msg)                                                                                                                                            ││   638                                                                                                                                                                               │╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯OSError: [Errno 32] Broken pipe

FFMPEG COMMAND:
S:\KI\Vladmandic1111\venv\lib\site-packages\imageio_ffmpeg\binaries\ffmpeg-win64-v4.2.2.exe -y -f rawvideo -vcodec rawvideo -s 1195x849 -pix_fmt rgb24 -r 30.00 -i - -an -vcodec       
libx264 -pix_fmt yuv420p -v warning S:\KI\Vladmandic1111\infinite-zooms\infinite_zoom_1682034171.mp4

FFMPEG STDERR OUTPUT:

Traceback (most recent call last):
  File "S:\KI\Vladmandic1111\venv\lib\site-packages\gradio\blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:\KI\Vladmandic1111\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\KI\Vladmandic1111\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "S:\KI\Vladmandic1111\venv\lib\site-packages\gradio\blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

**Comment by GeorgLegato** [comment]
tested with auto1111 and vlad1111. input size 720x512, scale 1,66 and 2.0 all passing
