### ISSUE TITLE
Having issue using 4x-Ultrasharp in postprocessing

### ISSUE THREAD

**Issue by JerryOver** [v8hid/infinite-zoom-automatic1111-webui#52]
I'm having an issue upscaling with 4x-Ultrasharp in postprocessing. This is the total progress after after batch 1 and then the error:
Batch 1/1
  0% 0/50 [00:00<?, ?it/s]
  2% 1/50 [00:00<00:07,  6.55it/s]
  4% 2/50 [00:00<00:07,  6.64it/s]
  6% 3/50 [00:00<00:07,  6.62it/s]
  8% 4/50 [00:00<00:06,  6.68it/s]
 10% 5/50 [00:00<00:06,  6.72it/s]
 12% 6/50 [00:00<00:06,  6.72it/s]
 14% 7/50 [00:01<00:06,  6.67it/s]
 16% 8/50 [00:01<00:06,  6.70it/s]
 18% 9/50 [00:01<00:06,  6.70it/s]
 20% 10/50 [00:01<00:05,  6.70it/s]
 22% 11/50 [00:01<00:05,  6.71it/s]
 24% 12/50 [00:01<00:05,  6.72it/s]
 26% 13/50 [00:01<00:05,  6.72it/s]
 28% 14/50 [00:02<00:05,  6.70it/s]
 30% 15/50 [00:02<00:05,  6.70it/s]
 32% 16/50 [00:02<00:05,  6.71it/s]
 34% 17/50 [00:02<00:04,  6.69it/s]
 36% 18/50 [00:02<00:04,  6.68it/s]
 38% 19/50 [00:02<00:04,  6.68it/s]
 40% 20/50 [00:02<00:04,  6.67it/s]
 42% 21/50 [00:03<00:04,  6.67it/s]
 44% 22/50 [00:03<00:04,  6.65it/s]
 46% 23/50 [00:03<00:04,  6.67it/s]
 48% 24/50 [00:03<00:03,  6.69it/s]
 50% 25/50 [00:03<00:03,  6.68it/s]
 52% 26/50 [00:03<00:03,  6.68it/s]
 54% 27/50 [00:04<00:03,  6.66it/s]
 56% 28/50 [00:04<00:03,  6.69it/s]
 58% 29/50 [00:04<00:03,  6.67it/s]
 60% 30/50 [00:04<00:02,  6.67it/s]
 62% 31/50 [00:04<00:02,  6.67it/s]
 64% 32/50 [00:04<00:02,  6.69it/s]
 66% 33/50 [00:04<00:02,  6.64it/s]
 68% 34/50 [00:05<00:02,  6.64it/s]
 70% 35/50 [00:05<00:02,  6.63it/s]
 72% 36/50 [00:05<00:02,  6.67it/s]
 74% 37/50 [00:05<00:01,  6.64it/s]
 76% 38/50 [00:05<00:01,  6.64it/s]
 78% 39/50 [00:05<00:01,  6.63it/s]
 80% 40/50 [00:05<00:01,  6.65it/s]
 82% 41/50 [00:06<00:01,  6.65it/s]
 84% 42/50 [00:06<00:01,  6.59it/s]
 86% 43/50 [00:06<00:01,  6.60it/s]
 88% 44/50 [00:06<00:00,  6.54it/s]
 90% 45/50 [00:06<00:00,  6.53it/s]
 92% 46/50 [00:06<00:00,  6.42it/s]
 94% 47/50 [00:07<00:00,  6.43it/s]
 96% 48/50 [00:07<00:00,  6.54it/s]
 98% 49/50 [00:07<00:00,  6.60it/s]
100% 50/50 [00:07<00:00,  6.65it/s]
Error completing request
Arguments: ([[0, ' ((Best quality)), ((masterpiece)),((realistic)),lord of the rings hobbit village, blue sky on top, scenic, masterpiece'], ['3', '((Best quality)), ((masterpiece)),((realistic)),lord of the rings lush green mountain forest with small river, blue sky on top, scenic, masterpiece'], ['6', '((Best quality)), ((masterpiece)),((realistic)),lord of the rings mountain valley in the alps, blue sky on top, scenic, masterpiece']], 'frames, borderline, text, character, duplicate, error, out of frame, watermark, low quality, ugly, deformed, blur  bad-artist', 8, 7, 50, None, None, 30, 1, 0, 0, 1, 0, 2, False, 0, 2, 512, 512, 1, 'Euler a', True, '4x-UltraSharp', 2) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py", line 242, in create_zoom
    result = create_zoom_single(
  File "/content/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py", line 352, in create_zoom_single
    do_upscaleImg(current_image, upscale_do, upscaler_name, upscale_by)
  File "/content/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py", line 102, in do_upscaleImg
    ups.process(
  File "/content/stable-diffusion-webui/scripts/postprocessing_upscale.py", line 94, in process
    upscaled_image = self.upscale(pp.image, pp.info, upscaler1, upscale_mode, upscale_by, upscale_to_width, upscale_to_height, upscale_crop)
  File "/content/stable-diffusion-webui/scripts/postprocessing_upscale.py", line 64, in upscale
    image = upscaler.scaler.upscale(image, upscale_by, upscaler.data_path)
  File "/content/stable-diffusion-webui/modules/upscaler.py", line 63, in upscale
    img = self.do_upscale(img, selected_model)
  File "/content/stable-diffusion-webui/modules/esrgan_model.py", line 154, in do_upscale
    img = esrgan_upscale(model, img)
  File "/content/stable-diffusion-webui/modules/esrgan_model.py", line 225, in esrgan_upscale
    output = upscale_without_tiling(model, tile)
  File "/content/stable-diffusion-webui/modules/esrgan_model.py", line 204, in upscale_without_tiling
    output = model(img)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/modules/esrgan_model_arch.py", line 62, in forward
    return self.model(feat)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 201, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 935, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

I use a colab. I don't know if that has anything to do with it. I have already created other infinite zoom videos, so this the next thing I am testing.

**Comment by GeorgLegato** [comment]
LORA is maybe the key here.
please provide prompts ("export prompt" or screenshot). I assume you use a LORA in your prompts.
If yo, please try again with easy prompt "like 0,cat,1,dog"

**Comment by JerryOver** [comment]
I ran it again without the LORA prompt. It gave the same error messages for 4x-Ultrasharp, so I ran it with upscalers Lanczos and Nearest. They worked, but I prefer to use 4x-Ultrasharp.

**Comment by GeorgLegato** [comment]
ok, btw automatic is dedicated strictly to python 3.10.6
you run for some reason 3.9
maybe you clean your venv and setup it new to ensure basic compatibility 

on our dev machines is nonissue about 4x uktrasharo, so therefore i assume some specific reason on your setup. let try the ox 3.10.6 now

**Comment by JerryOver** [comment]
I didn't create the colab. It was made Camenduru.

**Comment by GeorgLegato** [comment]
sorry, we support only Automatic1111 and since recent days Vladmandics fork.
collabs and derivates or completely differten platforms COULD work, but I dont see we cant support em all
![image](https://user-images.githubusercontent.com/7210708/234656937-6d981611-e0b1-47cb-91b7-ba38e057525f.png)
