### ISSUE TITLE
 'NoneType' object has no attribute 'alwayson_scripts'

### ISSUE THREAD

**Issue by athrony** [v8hid/infinite-zoom-automatic1111-webui#65]
Error completing request
Arguments: ([[0, 'Jungle with lush green trees and clear blue sky'], ['3', 'Jungle with tall brown trees and orange sunset sky'], ['5', 'Jungle with sparse trees and dark stormy sky'], ['10', 'Jungle with yellow autumn trees and purple twilight sky']], 'frames, borderline, text, character, duplicate, error, out of frame, watermark, low quality, ugly, deformed, blur  bad-artist', 14, 7, 50, None, None, 30, 0, 0, 0, 1, 0, 2, False, 0, 1, 512, 512, 1, 'Euler a', False, 'None', 1) {}
Traceback (most recent call last):
  File "E:\tools\stable\novelai-webui-aki-v3A\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\tools\stable\novelai-webui-aki-v3A\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\tools\stable\novelai-webui-aki-v3A\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 242, in create_zoom
    result = create_zoom_single(
  File "E:\tools\stable\novelai-webui-aki-v3A\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 330, in create_zoom_single
    processed = renderTxt2Img(
  File "E:\tools\stable\novelai-webui-aki-v3A\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 132, in renderTxt2Img
    processed = process_images(p)
  File "E:\tools\stable\novelai-webui-aki-v3A\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "E:\tools\stable\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 39, in processing_process_images_hijack
    cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
  File "E:\tools\stable\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 184, in get_cn_batches
    units = external_code.get_all_units_in_processing(p)
  File "E:\tools\stable\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\external_code.py", line 104, in get_all_units_in_processing
    return get_all_units(p.scripts, p.script_args)
  File "E:\tools\stable\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\external_code.py", line 113, in get_all_units
    cn_script = find_cn_script(script_runner)
  File "E:\tools\stable\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\external_code.py", line 280, in find_cn_script
    for script in script_runner.alwayson_scripts:
AttributeError: 'NoneType' object has no attribute 'alwayson_scripts'

Traceback (most recent call last):
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

**Comment by v8hid** [comment]
@nicholassun99 update your controlNet extension it will be fine
